displayName: GSSAPI Auth
type: middleware
iconPath: .assets/dog-ring.jpg

import: github.com/freddo3000/traefik-gssapi

summary: 'GSSAPI Authentication Middleware'

testData:
  Keytab: '/etc/krb5.keytab'
